
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.1.0
    
    # Workaround
    - name: Checkout private tools
      uses: actions/checkout@v2
      with:
        repository: qilingframework/theme.qiling.io
        path: themes/aircv
        submodule: recursive
   
    - name: Install Dependencies
      run: cd themes/aircv && yarn add hexo-renderer-scss hexo-filter-responsive-images imageinfo js-yaml && cd ../../

    - name: Deploy
      id: deploy
      uses: sma11black/hexo-action@v1.0.0
      with:
          user_name: lazymio
          user_email: mio@lazym.io
          deploy_key: ${{ secrets.QILING_IO_DKEY }}

    - name: Get the output
      run: |
        echo "${{ steps.deploy.outputs.notify }}"
