
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout qiling.io
      uses: actions/checkout@v2.1.0
    
    # Workaround
    - name: Checkout themes
      uses: actions/checkout@v2
      with:
        repository: qilingframework/theme.qiling.io
        path: themes/aircv
        submodule: recursive
   
    - name: Install Dependencies
      run: cd themes/aircv && yarn install && cd ../../
    
    - name: Install Hexo
      run: npm install hexo-cli && npm install hexo-deployer-git --save
   
    - name: Setup git
      run: git config --local user.email mio@lazym.io && git config --local user.name lazymio

    - name: Setup ssh
      run: mkdir -p ~/.ssh/ && echo "$QILING_IO_DKEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

    - name: Deploy
      run: npx hexo g -d

    - name: Get the output
      run: |
        echo "${{ steps.deploy.outputs.notify }}"
